-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "avgPx" DECIMAL(36,8),
ADD COLUMN     "execution" JSONB,
ADD COLUMN     "filledSize" DECIMAL(36,8) NOT NULL DEFAULT 0,
ADD COLUMN     "isBuy" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "simulated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tif" TEXT NOT NULL DEFAULT 'Ioc',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
