/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              ok: true;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/passkey/register/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description PublicKeyCredential{Creation,Request}OptionsJSON — pass to @simplewebauthn/browser */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              challenge: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/passkey/register/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Verifies the attestation, creates the user, sets the session cookie. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description RegistrationResponseJSON / AuthenticationResponseJSON from @simplewebauthn/browser */
      requestBody: {
        content: {
          'application/json': {
            id: string;
            rawId: string;
            /** @enum {string} */
            type: 'public-key';
            response: {
              [key: string]: unknown;
            };
          } & {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              userId: string;
              tempoAddress: string;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/passkey/login/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description PublicKeyCredential{Creation,Request}OptionsJSON — pass to @simplewebauthn/browser */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              challenge: string;
            } & {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/passkey/login/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Verifies the assertion and sets the session cookie. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description RegistrationResponseJSON / AuthenticationResponseJSON from @simplewebauthn/browser */
      requestBody: {
        content: {
          'application/json': {
            id: string;
            rawId: string;
            /** @enum {string} */
            type: 'public-key';
            response: {
              [key: string]: unknown;
            };
          } & {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              userId: string;
              tempoAddress: string;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              userId: string;
              tempoAddress: string;
              region: string | null;
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/region': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description ISO 3166-1 alpha-2 */
            region: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              region: string | null;
              hedge:
                | {
                    /** @enum {boolean} */
                    eligible: true;
                  }
                | {
                    /** @enum {boolean} */
                    eligible: false;
                    reason: string;
                  };
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tempo/sponsor': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Fee-payer relay: co-signs txs sent by tyr users. Use as the relay transport of withRelay(). */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description JSON-RPC request/response (Tempo fee-payer relay) */
      requestBody: {
        content: {
          'application/json': unknown;
        };
      };
      responses: {
        /** @description JSON-RPC request/response (Tempo fee-payer relay) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
        /** @description JSON-RPC request/response (Tempo fee-payer relay) */
        '4XX': {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
        /** @description JSON-RPC request/response (Tempo fee-payer relay) */
        '5XX': {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/limits/prepare': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Mints a tyr-held access key; the passkey then authorizes it on-chain with this spend limit. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            amountUsd: number;
            /** @enum {string} */
            period: 'day' | 'week';
          };
        };
      };
      responses: {
        /** @description Arguments for viem/tempo Actions.accessKey.authorize, signed by the passkey */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              accessKey: {
                accessKeyAddress: string;
                /** @enum {string} */
                keyType: 'p256' | 'secp256k1';
              };
              /** @description unix seconds */
              expiry: number;
              limits: {
                token: string;
                /** @description token base units (6 decimals) */
                limit: string;
                /** @description seconds */
                period: number;
              }[];
              limitId: string;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/limits/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Records the on-chain authorization after checking it on Moderato. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            limitId: string;
            txHash: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              limitId: string;
              remainingUsd: number;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/limits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              limit: {
                id: string;
                period: string;
                amountUsd: number;
                remainingUsd: number;
                periodEnd: number | null;
                authorizedTx: string | null;
              } | null;
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/markets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Featured outcome markets: unresolved, two-sided YES book right now. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              markets: components['schemas']['Market'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/markets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MarketDetail'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/revenue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Builder fee earned: HL referral state (live) and tyr ledger (live vs paper). */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              builder: string;
              feeTenthsBps: number;
              hl: {
                builderRewardsUsd: number;
              };
              ledger: {
                live: {
                  orders: number;
                  feesUsd: number;
                };
                simulated: {
                  orders: number;
                  feesUsd: number;
                };
              };
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              bets: components['schemas']['Order'][];
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Place a bet (Flow A). 402 = loss limit exceeded on-chain, 409 = insufficient confidential balance. Replaying an idempotencyKey returns the same order. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            outcome: number;
            /** @enum {string} */
            side: 'yes' | 'no';
            stakeUsd: number;
            idempotencyKey: string;
            maxPrice?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              sessions: {
                id: string;
                name: string | null;
                agentAddress: string;
                capUsd: number;
                spentUsd: number;
                period: string;
                /** Format: date-time */
                expiresAt: string;
                /** Format: date-time */
                revokedAt: string | null;
                authorizedTx: string | null;
                active: boolean;
                remainingUsd: number | null;
              }[];
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Register an agent key with a spend cap; the passkey then authorizes it on-chain. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            agentAddress: string;
            capUsd: number;
            /**
             * @default day
             * @enum {string}
             */
            period?: 'day' | 'week';
            name?: string;
            /** @default 30 */
            expiresInDays?: number;
          };
        };
      };
      responses: {
        /** @description Arguments for viem/tempo Actions.accessKey.authorize, signed by the passkey */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              accessKey: {
                accessKeyAddress: string;
                /** @enum {string} */
                keyType: 'p256' | 'secp256k1';
              };
              /** @description unix seconds */
              expiry: number;
              limits: {
                token: string;
                /** @description token base units (6 decimals) */
                limit: string;
                /** @description seconds */
                period: number;
              }[];
              sessionId: string;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/sessions/{id}/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            txHash: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              sessionId: string;
              remainingUsd: number;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Stops tyr serving the agent; revoke the on-chain key with the passkey. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              sessionId: string;
              /** @enum {boolean} */
              revoked: true;
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              name: string | null;
              agentAddress: string;
              capUsd: number;
              spentUsd: number;
              period: string;
              /** Format: date-time */
              expiresAt: string;
              /** Format: date-time */
              revokedAt: string | null;
              authorizedTx: string | null;
              active: boolean;
              owner: string;
              remainingUsd: number;
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/markets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              markets: components['schemas']['Market'][];
              priceUsd: {
                data: number;
              };
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/markets/{id}/data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Paid ($0.01): full two-sided books for one outcome market. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              market: components['schemas']['MarketDetail'];
              books: {
                yes: {
                  coin: string;
                  time: number;
                  /** @description [bids, asks] */
                  levels: {
                    px: string;
                    sz: string;
                    n: number;
                  }[][];
                } & {
                  [key: string]: unknown;
                };
                no: {
                  coin: string;
                  time: number;
                  /** @description [bids, asks] */
                  levels: {
                    px: string;
                    sz: string;
                    n: number;
                  }[][];
                } & {
                  [key: string]: unknown;
                };
              };
              paymentTx: string;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description HTTP 402 MPP challenge (WWW-Authenticate: Payment …); pay on Tempo Moderato and retry */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/evidence/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Paid ($0.01): on-chain evidence trail for one of this agent's bets. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              order: components['schemas']['Order'];
              links: {
                tempoStake: string | null;
                tempoPayout: string | null;
              };
              paymentTx: string;
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description HTTP 402 MPP challenge (WWW-Authenticate: Payment …); pay on Tempo Moderato and retry */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/bets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Paid: the MPP charge (= stake) is capped on-chain by the session, then Flow A runs. Replaying an idempotencyKey returns the same order (200) without a new charge. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            outcome: number;
            /** @enum {string} */
            side: 'yes' | 'no';
            stakeUsd: number;
            idempotencyKey: string;
            maxPrice?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description HTTP 402 MPP challenge (WWW-Authenticate: Payment …); pay on Tempo Moderato and retry */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/bets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/balance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Confidential tyrUSD balance, decrypted server-side for the owner only. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              availableUsd: number;
              /** @enum {string} */
              token: 'tyrUSD';
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/deposits/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              evm: {
                address: string;
                chains: string[];
                assets: {
                  [key: string]: string[];
                };
              };
              solana: {
                owner: string;
                usdcAta: string;
                usdcMint: string;
              };
              tempo: {
                to: string;
                memo: string;
                token: string;
              };
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/deposits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              deposits: components['schemas']['Deposit'][];
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/deposits/claim': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Claim an EVM deposit by tx hash (required for ETH). Credits inline when possible; the funding worker retries anything left uncredited. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            chain: 'sepolia' | 'baseSepolia' | 'arbSepolia' | 'robinhood';
            txHash: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              deposits: components['schemas']['Deposit'][];
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/zcash/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description ZIP-321 payment request for a shielded bet (Flow B). No account needed. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            outcome: number;
            /** @enum {string} */
            side: 'yes' | 'no';
            stakeUsd: number;
            returnUA: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description ZIP-321 payment URI (render as QR) */
              uri: string;
              to: string;
              zat: string;
              memo: string;
              zecUsd: number;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/zcash/orders/{txid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          txid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              txid: string;
              status: string;
              marketId: string;
              /** @enum {string} */
              side: 'yes' | 'no';
              /** @description decimal number as a string (exact, from Postgres numeric) */
              size: string;
              /** @description decimal number as a string (exact, from Postgres numeric) */
              zecUsd: string | null;
              payoutZat: string | null;
              payoutTxid: string | null;
              error: string | null;
              orderId: string | null;
            };
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/zcash/orders/{txid}/disclosure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description OVK view of the payout + FROST 2-of-3 check (the txid is the capability). */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          txid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              kind: 'zcash-ovk-view+frost';
              receiptId: string;
              orderTxid: string;
              payoutTxid: string;
              view: {
                [key: string]: unknown;
              } | null;
              instruction: {
                [key: string]: unknown;
              };
              frost: {
                signature: string;
                signers: string | null;
                verifyingKey: string;
                threshold: string;
                valid: boolean;
              };
              matches: boolean;
            };
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/zcash/orders/{txid}/receipt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          txid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              payloadHash: string;
              payload?: unknown;
              verification: components['schemas']['Verification'];
            };
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/hedge/markets/{marketId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Whether a hedge is offered for this market (drives the hedge card). */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          marketId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  /** @enum {boolean} */
                  offered: true;
                  stock: string;
                  token: string;
                  rule: string;
                  /** @enum {string} */
                  yesDirection: 'buy' | 'sell';
                  /** @enum {boolean} */
                  simulated: true;
                }
              | {
                  /** @enum {boolean} */
                  offered: false;
                };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/hedge/{orderId}/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Simulated swap quote for an open bet; amount defaults to the stake. */
    get: {
      parameters: {
        query?: {
          amountUsd?: number;
        };
        header?: never;
        path: {
          orderId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              simulated: true;
              orderId: string;
              stock: string;
              token: string;
              /** @enum {string} */
              direction: 'buy' | 'sell';
              rule: string;
              amountInUsd: number;
              maxAmountInUsd: number;
              entryPx: number;
              shares: number;
              priceSource: string;
              /** Format: date-time */
              priceAt: string;
              feeBps: number;
            };
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/hedge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              hedges: {
                orderId: string;
                userId: string;
                symbol: string;
                stockToken: string;
                /** @enum {string} */
                direction: 'buy' | 'sell';
                /** @description USD debited from the bankroll */
                amountIn: string;
                /** @description stock shares */
                amountOut: string;
                /** @description decimal number as a string (exact, from Postgres numeric) */
                entryPx: string;
                /** @description decimal number as a string (exact, from Postgres numeric) */
                exitPx: string | null;
                /** @description decimal number as a string (exact, from Postgres numeric) */
                valueUsd: string | null;
                priceSource: string;
                /** Format: date-time */
                priceAt: string;
                simulated: boolean;
                /** @enum {string} */
                status: 'open' | 'closed';
                uniswapTx: string | null;
                chainlinkRound: string | null;
                escrowTx: string | null;
                payTx: string | null;
                escrowTopUpTx: string | null;
                receiptId: string | null;
                receiptTx: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                closedAt: string | null;
                /** @description combined bet payout + hedge P&L, once the hedge is closed */
                receipt?: {
                  /** @enum {string} */
                  kind: 'bet+hedge';
                  orderId: string;
                  bet: {
                    [key: string]: unknown;
                  };
                  hedge: {
                    [key: string]: unknown;
                  };
                  netPnlUsd: number;
                  id: string | null;
                  payloadHash?: string;
                  tempoMemoTx: string | null;
                };
              }[];
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Open a hedge on an open bet: real confidential debit, simulated swap. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            orderId: string;
            amountUsd?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Hedge'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/hedge/{orderId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orderId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              orderId: string;
              userId: string;
              symbol: string;
              stockToken: string;
              /** @enum {string} */
              direction: 'buy' | 'sell';
              /** @description USD debited from the bankroll */
              amountIn: string;
              /** @description stock shares */
              amountOut: string;
              /** @description decimal number as a string (exact, from Postgres numeric) */
              entryPx: string;
              /** @description decimal number as a string (exact, from Postgres numeric) */
              exitPx: string | null;
              /** @description decimal number as a string (exact, from Postgres numeric) */
              valueUsd: string | null;
              priceSource: string;
              /** Format: date-time */
              priceAt: string;
              simulated: boolean;
              /** @enum {string} */
              status: 'open' | 'closed';
              uniswapTx: string | null;
              chainlinkRound: string | null;
              escrowTx: string | null;
              payTx: string | null;
              escrowTopUpTx: string | null;
              receiptId: string | null;
              receiptTx: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              closedAt: string | null;
              /** @description combined bet payout + hedge P&L, once the hedge is closed */
              receipt?: {
                /** @enum {string} */
                kind: 'bet+hedge';
                orderId: string;
                bet: {
                  [key: string]: unknown;
                };
                hedge: {
                  [key: string]: unknown;
                };
                netPnlUsd: number;
                id: string | null;
                payloadHash?: string;
                tempoMemoTx: string | null;
              };
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/receipts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              receipts: components['schemas']['ReceiptSummary'][];
            };
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/receipts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Receipt payload + hash. Owner, or anyone if the receipt is public; 404 otherwise. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              kind: ('bet' | 'zcash-payout' | 'bet+hedge') | string;
              subjectId: string | null;
              payloadHash: string;
              /** @enum {string} */
              visibility: 'private' | 'public';
              /** Format: date-time */
              createdAt: string;
              payload?: unknown;
            };
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/receipts/{id}/proof': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Prove bundle: Tempo tx + memo, Solana commitment opening + auditor attestation, Zcash OVK view + FROST. Owner, or anyone if the receipt is public; 404 otherwise. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Proof'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/receipts/{id}/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Re-checks the receipt against the chains (not the DB). Owner, or anyone if the receipt is public; 404 otherwise. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Verification'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/receipts/{id}/visibility': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Publish (proves first, so the public page serves the attested bundle) or hide. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            visibility: 'public' | 'private';
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReceiptSummary'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Error */
    Error: {
      error: string;
      /** @description machine-readable reason (e.g. limit, balance, region) */
      code?: string;
      /** @description request validation failures */
      issues?: {
        path: string;
        message: string;
      }[];
    };
    Order: {
      id: string;
      userId: string;
      agentSessionId: string | null;
      idempotencyKey: string | null;
      /** @description outcome id */
      hlMarket: string;
      /** @enum {string} */
      side: 'yes' | 'no';
      isBuy: boolean;
      tif: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      size: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      price: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      filledSize: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      avgPx: string | null;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      stakeUsd: string | null;
      stakeSalt: string | null;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      builderFee: string | null;
      hlOid: string | null;
      /** @description paper fill against the live HL testnet book */
      simulated: boolean;
      execution?: unknown;
      status: string;
      /** @description last completed saga step */
      step: string;
      error: string | null;
      tempoStakeTx: string | null;
      escrowTx: string | null;
      solanaOpenTx: string | null;
      parentId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      settlement?: components['schemas']['Settlement'] | null;
    };
    Settlement: {
      orderId: string;
      outcome: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      pnl: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      payoutUsd: string;
      payoutSalt: string | null;
      solanaTx: string | null;
      escrowPayTx: string | null;
      escrowTopUpTx: string | null;
      tempoPayoutTx: string | null;
      memoHash: string | null;
      closeOrderId: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    Deposit: {
      id: string;
      userId: string;
      sourceChain: string;
      sourceTx: string;
      logIndex: number;
      asset: string;
      /** @description USD credited */
      amount: string;
      rawAmount: string | null;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      fxRate: string | null;
      fxRound: string | null;
      status: ('confirmed' | 'minted' | 'credited') | string;
      mintTx: string | null;
      solanaTx: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      creditedAt: string | null;
    };
    Market: {
      outcome: number;
      name: string;
      description: string;
      template: {
        [key: string]: string;
      } | null;
      sides: string[];
      /** Format: date-time */
      resolvesAt: string;
      yes: {
        coin: string;
        bid: number;
        ask: number;
        mid: number;
      };
    };
    MarketDetail: {
      outcome: {
        outcome: number;
        name: string;
        description: string;
        sideSpecs: ({
          name: string;
        } & {
          [key: string]: unknown;
        })[];
        quoteToken?: string;
        venue?: string;
      } & {
        [key: string]: unknown;
      };
      /** Format: date-time */
      resolvesAt: string | null;
      books: {
        yes: {
          coin: string;
          time: number;
          /** @description [bids, asks] */
          levels: {
            px: string;
            sz: string;
            n: number;
          }[][];
        } & {
          [key: string]: unknown;
        };
        no: {
          coin: string;
          time: number;
          /** @description [bids, asks] */
          levels: {
            px: string;
            sz: string;
            n: number;
          }[][];
        } & {
          [key: string]: unknown;
        };
      };
    };
    Hedge: {
      orderId: string;
      userId: string;
      symbol: string;
      stockToken: string;
      /** @enum {string} */
      direction: 'buy' | 'sell';
      /** @description USD debited from the bankroll */
      amountIn: string;
      /** @description stock shares */
      amountOut: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      entryPx: string;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      exitPx: string | null;
      /** @description decimal number as a string (exact, from Postgres numeric) */
      valueUsd: string | null;
      priceSource: string;
      /** Format: date-time */
      priceAt: string;
      simulated: boolean;
      /** @enum {string} */
      status: 'open' | 'closed';
      uniswapTx: string | null;
      chainlinkRound: string | null;
      escrowTx: string | null;
      payTx: string | null;
      escrowTopUpTx: string | null;
      receiptId: string | null;
      receiptTx: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      closedAt: string | null;
    };
    ReceiptSummary: {
      id: string;
      kind: ('bet' | 'zcash-payout' | 'bet+hedge') | string;
      subjectId: string | null;
      payloadHash: string;
      /** @enum {string} */
      visibility: 'private' | 'public';
      /** Format: date-time */
      createdAt: string;
    };
    Verification: {
      receiptId: string;
      kind: string;
      ok: boolean;
      checks: {
        name: string;
        ok: boolean;
        detail?: string;
      }[];
    };
    Proof: {
      receiptId: string;
      kind: string;
      payloadHash: string;
      /** Format: date-time */
      provedAt: string;
      tempo: {
        label: string;
        tx: string;
        memo: string;
        explorer: string;
      }[];
      solana: {
        settleTx: string | null;
        opening: {
          amountUnits: string;
          salt: string;
        } | null;
        attestations: {
          label: string;
          tx: string;
          explorer: string;
          attestation: {
            statement: {
              [key: string]: unknown;
            };
          } & {
            [key: string]: unknown;
          };
        }[];
      } | null;
      zcash: {
        /** @enum {string} */
        kind: 'zcash-ovk-view+frost';
        receiptId: string;
        orderTxid: string;
        payoutTxid: string;
        view: {
          [key: string]: unknown;
        } | null;
        instruction: {
          [key: string]: unknown;
        };
        frost: {
          signature: string;
          signers: string | null;
          verifyingKey: string;
          threshold: string;
          valid: boolean;
        };
        matches: boolean;
      } | null;
    };
    /** @description Messages pushed on GET /ws (session cookie). Closes 4401 when unauthenticated. */
    WsEvent:
      | {
          /** @enum {string} */
          type: 'hello';
          userId: string;
        }
      | {
          /** @enum {string} */
          type: 'order';
          userId: string;
          orderId: string;
          step: string;
          status: string;
        }
      | {
          /** @enum {string} */
          type: 'settlement';
          userId: string;
          orderId: string;
          outcome: string;
          payoutUsd: number;
        }
      | {
          /** @enum {string} */
          type: 'deposit';
          userId: string;
          depositId: string;
          sourceChain: string;
          status: string;
          amountUsd: number;
        };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
